site_name: KochiOrgBook
theme:
  name: 'material'
extra_css:
  - stylesheets/extra.css

nav:
  - Informational:
    - 'Overview': 'index.md'
    - 'Mission': 'index.md'
    - 'Use Cases': 
      - 'Key Use Cases': 'gf_info/key_use_cases.md'
      - 'Generic Use Cases': 'gf_info/generic_use_cases.md'
    - 'KochiOrgBook – Community project initiative for the City of Kochi​': 'gf_info/community_initiative.md'
    - 'KochiOrgBook Sub Projects​': 'gf_info/sub_projects.md'
    - 'How to Contribute': 'gf_info/how to contribute.md'
    - 'Consortium': 'gf_info/consortium.md'
  - Constitutional:
    - 'Master Document': 'gf_info/master_doc.md'
    - Controlled:
      - 'Glossary': 'gf_controlled/glossary.md'
      - Legal:
        - Member Agreements: 'gf_legal/member_agreements.md'
      - Compliance:
        - 'Trust Assurance': 'gf_assurance/trust_assurance.md'
        


  
    

