site_name: KOB Mentorship Program 
theme:
    name: material
    # nav_style: dark
extra_css:
  - stylesheets/extra.css
nav:
  - KOB Mentorship Program: 'index.md'
  - Projects:
    - KOBAW: 'kobaw.md'
    - KOBConnect: 'kobconnect.md'
    - KOBPIU: 'kobpiu.md'
    - KOBVCR: 'kobvcr.md'
    - KOBCC: 'kobcc.md'
    - KOBVON: 'kobvon.md'
    - KOBSearch: 'kobsearch.md'
    - KOB Address Verification: 'kobavs.md'
    - KOB Phonenumber Verification: 'kobpvs.md'
    - KOB Email Verification: 'kobevs.md'
